import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/* Generated by esbuild. View source on GitHub. */`;
const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: ['obsidian', 'electron', ...builtinModules,
		'@codemirror/state', '@codemirror/view', '@codemirror/language'],
	format: 'cjs',
	target: 'es2021',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) { await context.rebuild(); process.exit(0); }
else      { await context.watch(); }
